SERPER_API_KEY: 5fc8495f7435fdda084d0b27ee8953ebfcca2b32

OPENAI_API_KEY: null

ANTHROPIC_API_KEY: null

LOCAL_API_KEY: null
LOCAL_API_URL: null

GEMINI_API_KEY : AIzaSyBpWSk88EPvwMUm_5-MaPkiR0RQ7bYrvJM